// Generated by Wrangler by running `wrangler types`

interface Env {
	USERS: DurableObjectNamespace<import("./src/index").UsersDo>;
}
declare module "*.sql" {
	const value: string;
	export default value;
}